name: Practica_GithubActions
on: 
  push:
   branches:
    - main
jobs:
  Github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons